export default [
  {
    EngName: "My Hero Academia",
    JpName: "Boku No Hero Academia",
    Date: "2016 - 2024",
    Genre: "Shonen",
    Picture: "./src/Anime/Pictures/bnha.jpg",
    ARating: "10/10",
    MRating: "-/10",
    Episode: "--Ep | 7Se",
    Description: "lorem lorem loremlorem lorem loremlorem lorem lorem",
    Rank: "#1",
  },

  {
    EngName: "FullMetal Alchemist: Brotherhood",
    JpName: "lorem",
    Date: "2011 - 2013",
    Genre: "Shonen",
    Picture: "src/",
    ARating: "10/10",
    MRating: "9/10",
    Episode: "64Ep | 1Se",
    Description: "lorem lorem lorem",
    Rank: "#2",
  },

  {
    EngName: "lorem",
    JpName: "lorem",
    Date: "2023 - 2024",
    Genre: "Shonen",
    Picture: "src/",
    ARating: "10/10",
    MRating: "9/10",
    Episode: "12Eps",
    Description: "lorem lorem lorem",
    Rank: "#3",
  },

  {
    EngName: "lorem",
    JpName: "lorem",
    Date: "2023 - 2024",
    Genre: "Shonen",
    Picture: "src/",
    ARating: "10/10",
    MRating: "9/10",
    Episode: "12Eps",
    Description: "lorem lorem lorem",
    Rank: "#4",
  },
];
